//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_ClientWCF.ReferenciasNegocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_Lista_Cliente_Result", Namespace="http://schemas.datacontract.org/2004/07/WEB_APP_010")]
    [System.SerializableAttribute()]
    public partial class usp_Lista_Cliente_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fonoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirCliente {
            get {
                return this.DirClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DirClienteField, value) != true)) {
                    this.DirClienteField = value;
                    this.RaisePropertyChanged("DirCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCliente {
            get {
                return this.NomClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClienteField, value) != true)) {
                    this.NomClienteField = value;
                    this.RaisePropertyChanged("NomCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePais {
            get {
                return this.NombrePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePaisField, value) != true)) {
                    this.NombrePaisField = value;
                    this.RaisePropertyChanged("NombrePais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fonoCliente {
            get {
                return this.fonoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.fonoClienteField, value) != true)) {
                    this.fonoClienteField = value;
                    this.RaisePropertyChanged("fonoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_Lista_Pedido_Result", Namespace="http://schemas.datacontract.org/2004/07/WEB_APP_010")]
    [System.SerializableAttribute()]
    public partial class usp_Lista_Pedido_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirDestinatario {
            get {
                return this.DirDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DirDestinatarioField, value) != true)) {
                    this.DirDestinatarioField = value;
                    this.RaisePropertyChanged("DirDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPedido {
            get {
                return this.FechaPedidoField;
            }
            set {
                if ((this.FechaPedidoField.Equals(value) != true)) {
                    this.FechaPedidoField = value;
                    this.RaisePropertyChanged("FechaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCliente {
            get {
                return this.NomClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClienteField, value) != true)) {
                    this.NomClienteField = value;
                    this.RaisePropertyChanged("NomCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciasNegocios.IServicioNegocios")]
    public interface IServicioNegocios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/Clientes", ReplyAction="http://tempuri.org/IServicioNegocios/ClientesResponse")]
        System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result> Clientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/Clientes", ReplyAction="http://tempuri.org/IServicioNegocios/ClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result>> ClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/ClienteXNombre", ReplyAction="http://tempuri.org/IServicioNegocios/ClienteXNombreResponse")]
        System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result> ClienteXNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/ClienteXNombre", ReplyAction="http://tempuri.org/IServicioNegocios/ClienteXNombreResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result>> ClienteXNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/PedidoXCliente", ReplyAction="http://tempuri.org/IServicioNegocios/PedidoXClienteResponse")]
        System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result> PedidoXCliente(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/PedidoXCliente", ReplyAction="http://tempuri.org/IServicioNegocios/PedidoXClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result>> PedidoXClienteAsync(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/PedidoXCodigo", ReplyAction="http://tempuri.org/IServicioNegocios/PedidoXCodigoResponse")]
        System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result> PedidoXCodigo(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocios/PedidoXCodigo", ReplyAction="http://tempuri.org/IServicioNegocios/PedidoXCodigoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result>> PedidoXCodigoAsync(int idPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioNegociosChannel : APP_ClientWCF.ReferenciasNegocios.IServicioNegocios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNegociosClient : System.ServiceModel.ClientBase<APP_ClientWCF.ReferenciasNegocios.IServicioNegocios>, APP_ClientWCF.ReferenciasNegocios.IServicioNegocios {
        
        public ServicioNegociosClient() {
        }
        
        public ServicioNegociosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNegociosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNegociosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNegociosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result> Clientes() {
            return base.Channel.Clientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result>> ClientesAsync() {
            return base.Channel.ClientesAsync();
        }
        
        public System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result> ClienteXNombre(string nombre) {
            return base.Channel.ClienteXNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Cliente_Result>> ClienteXNombreAsync(string nombre) {
            return base.Channel.ClienteXNombreAsync(nombre);
        }
        
        public System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result> PedidoXCliente(string cliente) {
            return base.Channel.PedidoXCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result>> PedidoXClienteAsync(string cliente) {
            return base.Channel.PedidoXClienteAsync(cliente);
        }
        
        public System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result> PedidoXCodigo(int idPedido) {
            return base.Channel.PedidoXCodigo(idPedido);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<APP_ClientWCF.ReferenciasNegocios.usp_Lista_Pedido_Result>> PedidoXCodigoAsync(int idPedido) {
            return base.Channel.PedidoXCodigoAsync(idPedido);
        }
    }
}
